export const videoItems = [
  {
    id: 1,
    title: "Cristiano Ronaldo",
    subtitle: "Portugal",
    icon: "🇵🇹",
    country: "Portugal",
    yearRange: "2002-Present",
    label: "Goals",
    rankNumber: 1,
    rankLabel: "Goals",
    mediaUrl: "https://i.pravatar.cc/300?img=1",
  },
  {
    id: 2,
    title: "Lionel Messi",
    subtitle: "Argentina",
    icon: "🇦🇷",
    country: "Argentina",
    yearRange: "2004-Present",
    label: "Goals",
    rankNumber: 2,
    rankLabel: "Goals",
    mediaUrl: "https://i.pravatar.cc/300?img=2",
  },
  {
    id: 3,
    title: "Pelé",
    subtitle: "Brazil",
    icon: "🇧🇷",
    country: "Brazil",
    yearRange: "1956-1977",
    label: "Goals",
    rankNumber: 3,
    rankLabel: "Goals",
    mediaUrl: "https://i.pravatar.cc/300?img=3",
  },
  {
    id: 4,
    title: "Romário",
    subtitle: "Brazil",
    icon: "🇧🇷",
    country: "Brazil",
    yearRange: "1985-2008",
    label: "Goals",
    rankNumber: 4,
    rankLabel: "Goals",
    mediaUrl: "https://i.pravatar.cc/300?img=4",
  },
  {
    id: 5,
    title: "Ferenc Puskás",
    subtitle: "Hungary",
    icon: "🇭🇺",
    country: "Hungary",
    yearRange: "1943-1966",
    label: "Goals",
    rankNumber: 5,
    rankLabel: "Goals",
    mediaUrl: "https://i.pravatar.cc/300?img=5",
  },
];
