<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $password = Hash::make('123');

        $users = [
            [
                'id'                => 1,
                'name'              => 'Hamza Ali',
                'email'             => 'hamzataskly@mail.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'gNCfw0jVXB17hOHJwvPXX2dIir254cgkbmloDe0KjYaTVRAkss5tXxn8iGfj',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 2,
                'name'              => 'Atif Aslam',
                'email'             => 'atif@mail.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'eFcDBHsNOeUCscjAnrFtNWvhiZCs1KnSyvAHaMOgeOK6I4qalxV7eHj9uhBn',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 3,
                'name'              => 'Deborah Green V',
                'email'             => 'bartell.hermann@example.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'oNsyfJqax7rd0pWko6M1OFLaqm488jg3TCEINeZE0SRtyIuaVl9KS6Gcu0kH',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 4,
                'name'              => 'Joany Wilkinson',
                'email'             => 'celestine.goyette@example.org',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'e1xUxLtRkr',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 5,
                'name'              => 'Jolie Pfeffer',
                'email'             => 'jodie66@example.net',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'EzYeRsG9sY',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 6,
                'name'              => 'Prof. Andreanne Tromp',
                'email'             => 'stokes.crystel@example.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => '2eIDoXDbJj',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 7,
                'name'              => 'Dr. Gwen Olson',
                'email'             => 'lexus.wuckert@example.org',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'YKuUqSXBqp',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 8,
                'name'              => 'Gustave Kassulke PhD',
                'email'             => 'reggie.greenfelder@example.net',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'JTCCSLUA7i',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 9,
                'name'              => 'Janick VonRueden',
                'email'             => 'harris.jensen@example.net',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'vbRYybrO6i',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 10,
                'name'              => 'Abbas Raza',
                'email'             => 'abbas@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => '2tjMGUVBReoGntKxRp1dtNHoJehwr22odVyr0osuahGTijHWU6tWrr79ZyXY',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2025-04-30 12:03:45',
            ],
            [
                'id'                => 11,
                'name'              => 'PGRN Admin',
                'email'             => 'data@pgrn.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'aXsiz3qemZlY2RlsKEbbWG0OucRLY5wNNugkMub0mHLvbqzuzdu8tBatgqTn',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 12,
                'name'              => 'Alltm Admin',
                'email'             => 'data@alltm.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'vZWJBXqUBrDFlvlFaLJMBKO4JIar56zgP9IuFnHyNsTbO2QCuN48etn2BoFM',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 13,
                'name'              => 'Waseem Abbas',
                'email'             => 'waseem@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'Fu8R26bKAcHCA3rslh8nGkrhHjzLXSqWYw0VcQ3Qhc7ZfRop3RA2AFSD73rj',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2025-09-22 07:05:06',
            ],
            [
                'id'                => 14,
                'name'              => 'Kamran Akram',
                'email'             => 'kamran@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'kwhaQyxA17tqCS5GvhAz8wJ9NJl8UNmyvB7OWoTS2iUvjMOUWq5o6CmppSme',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2025-09-22 06:18:46',
            ],
            [
                'id'                => 15,
                'name'              => 'Kisa Batool',
                'email'             => 'kisa@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'tLsO48wry7bx8RxRNXhH2SwpD0nJdz0rWkO8u2WwOHMuAUhJbt3smrb4QIfn',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 16,
                'name'              => 'M Abubakr',
                'email'             => 'abubakr@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'VQy1uswxOenQnxyuEmDlrDwoZfqxDeF517Aaw93pie8hsJCUC1nP2nXUVmnL',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 17,
                'name'              => 'Softleed Admin',
                'email'             => 'softleed@gmail.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => '7CdShp3xqvBxU8TP8UAjVKgPyl4KeYkJjWeOMPd3Psbotu6xjo1RkdmI3Qt5',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 18,
                'name'              => 'Dua Khalid',
                'email'             => 'dua@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'MU1AwlbTKae9VkijnPfC0EG3YGmoHA7DS9R7Ca7GMG09Pslu4z7wztSYRmmx',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 19,
                'name'              => 'Muzna Ahmad',
                'email'             => 'muzna@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'TuzWqZjyiAk9SQEmt8PUsX87iOIZfHj8VFMWN3Vvu7bmTYOhIWVFDFgI9QuD',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2024-06-09 09:28:31',
            ],
            [
                'id'                => 20,
                'name'              => 'Dua Khalid',
                'email'             => 'khaliddua876@gmail.com',
                'email_verified_at' => '2025-01-25 01:29:01',
                'password'          => $password,
                'remember_token'    => 'ZONNZ2djm1pMMT4u7D3s8cNHIt7h3DUlFhbzqEeESYrW9DNnt6c41O98sas8',
                'created_at'        => '2025-01-25 01:27:01',
                'updated_at'        => '2025-01-25 01:29:01',
            ],
            [
                'id'                => 21,
                'name'              => 'Abubakar Ahmad',
                'email'             => 'abubakarlala061@gmail.com',
                'email_verified_at' => '2025-01-31 02:10:18',
                'password'          => $password,
                'remember_token'    => 'JF0z2d9XEbDrnqZ52fdKHKCD0wBqePSwSWtc7wGXGH9ZdnQqz9fPu38va1bs',
                'created_at'        => '2025-01-31 02:09:48',
                'updated_at'        => '2025-04-09 09:28:15',
            ],
            [
                'id'                => 22,
                'name'              => 'Admin',
                'email'             => 'admin@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'ZWkkjGc2WrnrrU6k94hIoJstFamqaxWjgH7DEyukcZzyHd6Nc0nsY57BoT2y',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2025-01-18 14:13:23',
            ],
            [
                'id'                => 23,
                'name'              => 'Zain Zaidi',
                'email'             => 'zain4886@gmail.com',
                'email_verified_at' => '2025-02-14 12:18:38',
                'password'          => $password,
                'remember_token'    => 'GZtd3vHmHvPiYT0HK33LVVzv9zPpvTRoMRupr7yMRwR9fupSt64o7HDZuVHJ',
                'created_at'        => '2025-02-14 12:16:26',
                'updated_at'        => '2025-02-14 12:18:38',
            ],
            [
                'id'                => 25,
                'name'              => 'Taimoor',
                'email'             => 'taimoor.6189@gmail.com',
                'email_verified_at' => '2025-02-23 00:35:20',
                'password'          => $password,
                'remember_token'    => 'kzYKECmKaUrMZLQ4JZM26Hw3DRFGtnYYENhI7rtcZyBNrxmteAdtbUDsmJrE',
                'created_at'        => '2025-02-23 00:34:01',
                'updated_at'        => '2025-02-23 00:35:42',
            ],
            [
                'id'                => 30,
                'name'              => 'Sarbaz Mehdi',
                'email'             => 'sarbaz@softleed.com',
                'email_verified_at' => '2025-04-14 11:03:26',
                'password'          => $password,
                'remember_token'    => 'Yw5RRIuPTDCgl126gtW56Kb2DUTyrcOjANeqvrhhvg7MsqjzGWfL1MIYoE9m',
                'created_at'        => '2025-04-14 11:02:57',
                'updated_at'        => '2025-04-15 03:02:21',
            ],
            [
                'id'                => 31,
                'name'              => 'Imran Abbas',
                'email'             => 'imranabbassiddiqui@gmail.com',
                'email_verified_at' => '2025-04-19 05:15:53',
                'password'          => $password,
                'remember_token'    => 'RHLEyH9iSGiJhQFyecPr3zrMX8Gra0wHD0KNbL13ZtiHDKTtaMamUHCksLkn',
                'created_at'        => '2025-04-19 05:15:06',
                'updated_at'        => '2025-04-19 05:16:06',
            ],
            [
                'id'                => 32,
                'name'              => 'Muhammad Ahtasham',
                'email'             => 'm.ahtashamsaddique@gmail.com',
                'email_verified_at' => '2025-05-12 04:20:05',
                'password'          => $password,
                'remember_token'    => 'TYVpuDRnGLd20Ym6tawvgiBsIPb9PUtt1OikqNU1PrOIF4kORbG9dMXRGlno',
                'created_at'        => '2025-05-12 04:18:54',
                'updated_at'        => '2025-05-13 01:23:45',
            ],
            [
                'id'                => 33,
                'name'              => 'Syeda Kisa Batool',
                'email'             => 'syedaaaria@gmail.com',
                'email_verified_at' => '2025-05-12 04:42:10',
                'password'          => $password,
                'remember_token'    => 'qBEz3TDqi3mvTc1QWzav55AX0v79aRyC3ZwdTU2nPfEesXfRcLrghptax8lh',
                'created_at'        => '2025-05-12 04:40:49',
                'updated_at'        => '2025-05-12 04:42:35',
            ],
            [
                'id'                => 35,
                'name'              => 'Ali Raza',
                'email'             => 'client@softleed.com',
                'email_verified_at' => '2025-08-28 08:42:42',
                'password'          => $password,
                'remember_token'    => '909pmzbbnE1PadG16KlZ7VFBO6X4t6AQ0Pn0LpxRzhKmUSqAm8SOBuzExCWD',
                'created_at'        => '2025-08-28 08:41:23',
                'updated_at'        => '2025-08-28 08:42:49',
            ],
            [
                'id'                => 37,
                'name'              => 'Waseem Abbas',
                'email'             => 'wasim@softleed.com',
                'email_verified_at' => '2024-06-09 09:28:31',
                'password'          => $password,
                'remember_token'    => 'lo7rrYMrln51sLoPELoHWlA3A7ZdlMoBdCtsiZiQ0eYRjViAJwpjno34l9Or',
                'created_at'        => '2024-06-09 09:28:31',
                'updated_at'        => '2025-09-22 07:05:06',
            ],
            [
                'id'                => 38,
                'name'              => 'NW Tech Solution',
                'email'             => 'emp-client@softleed.com',
                'email_verified_at' => '2025-10-04 01:21:19',
                'password'          => $password,
                'remember_token'    => null,
                'created_at'        => '2025-10-04 01:20:44',
                'updated_at'        => '2025-10-04 01:21:25',
            ],
        ];

        DB::table('users')->insert($users);

    }
}
